baseurl = "http://www.harth-lang.org/"
languageCode = "en-us"
title = "Harth Programming Language"
author = ["Harvey Thompson"]
disqusShortname = "610yesnolovely"
MetaDataFormat = "yaml"
theme = "harth-hugo-theme"
paginate = 10
pygmentsUseClasses = true
pygmentsCodeFences = true
GoogleAnalytics = "UA-71830715-3"

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    post = "/blog/:year/:month/:day/:title/"

[taxonomies]
    # Optional. Use if you want tags and lists.
    category = "categories"

[params]
    # If false display full article contents in blog index.
    # Otherwise show description and 'read on' link to individual blog post page.
    # Default (if omitted) is true.
    truncate = true

    title_html = "Harth<br>Programming<br>Language"
    description = "Harth Programming Language"
    author = "Harvey Thompson"
    author_url = "http://www.610yesnolovely.org"
    generator = "Hugo 0.15"

    # Sidebar-bot.html social links, full URLs!
    twitter = "https://twitter.com/610yesnolovely"
    github = "https://github.com/harthsw"
    bitbucket = "https://bitbucket.org/harthsw"
    email = "harth-lang@harthsw.com"
    rss = true
    # stackOverflow = "..."
    # linkedin = "..."
    # googleplus = "..."
    # facebook = "..."
    # youtube = "..."

[menu]

[[menu.main]]
  name = "Home"
  identifier = "mn_home"
  url = "/"
  weight = 1

# [[menu.main]]
#   name = "Language Reference"
#   identifier = "mn_ref"
#   url = "/ref/"
#   weight = 2

# [[menu.main]]
#   name = "Language API"
#   identifier = "mn_api"
#   url = "/api/"
#   weight = 3

[[menu.main]]
  name = "Blog"
  identifier = "mn_blog"
  url = "/post/"
  weight = 4

[[menu.main]]
  name = "License"
  url = "/license/"
  weight = 5
